server:
  port: 9090
spring:
  application:
    name: banky
  datasource:
    url: jdbc:mysql://localhost:3306/banky?createDatabaseIfNotExist=true
    username: root
    password: Coder@9505
  jpa:
    hibernate:
     ddl-auto: update
  show-sql: true